"""autogen: add youtube/twitch limit overrides

Revision ID: 0831864a2940
Revises: 20260328_merge_heads_86193de34e59
Create Date: 2026-03-28 22:07:01.760904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0831864a2940'
down_revision: Union[str, Sequence[str], None] = '20260328_merge_heads_86193de34e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
