"""initial schema: users and jobs

Revision ID: 3b526031a41b
Revises: 3ce4eda8188c
Create Date: 2026-03-10 00:27:53.341821

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3b526031a41b"
down_revision: Union[str, Sequence[str], None] = "3ce4eda8188c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
