import { useEffect } from 'react'

export default function YoutubeShortsGenerator() {
  useEffect(() => {
    document.title = 'AI YouTube Shorts Generator'
    const desc = document.querySelector('meta[name="description"]')
    if (desc) desc.setAttribute('content', 'AI YouTube Shorts Generator - Automatically convert long YouTube videos into engaging Shorts, Reels and TikToks using AI.')
  }, [])

  return (
    <main className="max-w-4xl mx-auto px-6 py-16 text-white">
      <h1 className="text-4xl font-extrabold mb-6">AI YouTube Shorts Generator</h1>

      <p className="text-gray-300 leading-relaxed mb-4">
        AI YouTube Shorts Generator helps creators and brands transform long YouTube videos into short, attention-grabbing clips optimized for YouTube Shorts, TikTok and Instagram Reels. Using powerful AI models, the tool analyzes audio and visual signals to identify the most engaging moments, then automatically crops, reformats and captions each clip so it’s ready to publish.
      </p>

      <h2 className="text-2xl font-bold mt-6 mb-3">How it works</h2>
      <p className="text-gray-300 leading-relaxed mb-4">
        Paste a YouTube URL, choose a few options (length, number of clips), and let the AI do the rest. Our pipeline uses transcription and scoring to surface the moments with the highest likelihood to go viral — natural highlights, emotional peaks, punchlines and demonstrations. Clips are exported in vertical format with autogenerated captions.
      </p>

      <h2 className="text-2xl font-bold mt-6 mb-3">Why creators use it</h2>
      <p className="text-gray-300 leading-relaxed mb-4">
        Creators save hours of manual editing. The AI-driven YouTube shorts generator accelerates repurposing: more shorts per video, consistent quality, and faster publishing. Use cases include podcast highlights, tutorial snippets, product demos, and gaming highlights — all optimized for mobile-first viewers.
      </p>

      <p className="text-gray-300 leading-relaxed mt-6">
        Keywords: AI shorts generator, YouTube shorts generator, AI clip generator, YouTube video to shorts.
      </p>
    </main>
  )
}
